### ISSUE TITLE
Crash when using sqlite framework ??

### ISSUE THREAD

**Issue by zerozhu** [DyCI/dyci-main#83] opened 2015-05-12 06:50 UTC
my app has used sqlite database , after i add dyci framework , my app crashed. why ?

**Comment by PaulTaykalo** [comment] 2015-05-12 07:47
http://www.kith.org/logos/things/sitpuz/situations.html
> In the game of situation puzzles, a mysterious situation is presented to a group of players, who must then try to find out what's going on by asking further questions. The person who initially presented the situation can only answer "yes" or "no" to questions (or occasionally "irrelevant").

Short answer - because `dyci` broke something.  

If you can create an example project, where I can reproduce this issue, then, probably, this will be fixed.  
If not, then, you'll need to find the answer by yourself  

Also you can try to check this https://github.com/DyCI/dyci-main/wiki/Class-filtering-:-we-need-to-go-deeper

**Comment by zerozhu** [comment] 2015-05-13 09:20
Hello, thank you for answer my question. I just create an example project。  https://github.com/zerozhu/DyciSqliteDemo

When you remove reference of dyci.framework , it will not crash. 
you add dyci.framework, it will crash.

**Comment by PaulTaykalo** [comment] 2015-05-14 08:20
@zerozhu I've reproduced the crash.
This happens if `dyci.framework` is used as a workaround you can try to use cocoapods to integrate `dyci`

**Comment by PaulTaykalo** [comment] 2015-05-14 12:54
@zerozhu 
Fixed in https://github.com/DyCI/dyci-main/commit/823e92051a900a9d388933c2853bca1556e2d453  

//  Framework
https://github.com/DyCI/dyci-main/commit/123d8fef2d29c52880c2a0eb667c3438c59b6da0

Thanks

**Closed by PaulTaykalo** 2015-05-14 12:54 UTC
Labels: example project is needed

**Comment by zerozhu** [comment] 2015-05-18 02:07
OK, Thanks, I will try to use cocoapods to integrate dyci

**Comment by PaulTaykalo** [comment] 2015-05-18 08:15
@zerozhu It's already fixed, so feel free to use whatever you prefer
